import type { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "knela",
    title: "knelA",
    description:
      "Una herramienta de pedidos directos para bares y cafeterías, pensada para quitar fricción justo donde empieza la espera.",
    longDescription:
      "Tiene landing, demo, precios y un flujo completo para que un negocio pueda recibir pedidos en su propia mesa de trabajo.",
    highlights: [
      "Demo pública con un menú y pedido de prueba",
      "Producto con precios, onboarding y flujo de negocio",
      "Frontend y backend pensados para el uso diario",
    ],
    role: "Producto, frontend, backend y despliegue",
    category: "Producto",
    status: "Publicado",
    visibility: "principal",
    order: 1,
    stack: ["React", "TypeScript", "Vite", "Fastify", "Prisma"],
    liveUrl: "https://knela.es/",
    liveLabel: "Abrir knelA",
    featured: true,
    year: 2026,
  },
  {
    id: "tabs-organizer",
    title: "Branch Tabs Manager",
    description:
      "Extensión de VS Code que guarda y recupera las pestañas abiertas según la rama de Git.",
    highlights: [
      "Publicada en Visual Studio Marketplace",
      "Conserva el contexto al cambiar de rama",
      "Filtra por workspace y evita pestañas fantasma",
    ],
    role: "Producto, extensión y experiencia de desarrollo",
    category: "Herramienta",
    status: "Publicado",
    visibility: "principal",
    order: 2,
    stack: ["VS Code API", "TypeScript", "Git", "Node.js"],
    liveUrl:
      "https://marketplace.visualstudio.com/items?itemName=nel386.tabs-organizer",
    liveLabel: "Ver en Marketplace",
    repoUrl: "https://github.com/nel386/tabs-organizer",
    year: 2026,
  },
  {
    id: "impostor-game",
    title: "Impostor Game",
    description:
      "Un juego social para grupos: se reparten roles y palabras secretas desde un solo dispositivo.",
    highlights: [
      "Partidas rápidas sin cuentas ni preparación",
      "Diseño mobile-first con un flujo fácil de entender",
      "Branding propio y una landing ligera",
    ],
    role: "Frontend y UX",
    category: "Juego social",
    status: "Publicado",
    visibility: "principal",
    order: 3,
    stack: ["React", "TypeScript", "Vite"],
    liveUrl: "https://nel386.github.io/impostor-game/",
    liveLabel: "Jugar ahora",
    repoUrl: "https://github.com/nel386/impostor-game",
    year: 2026,
  },
  {
    id: "punto-medio",
    title: "Punto Medio",
    description:
      "Un juego de debate y escalas para Android y navegador, construido para discutir sin convertirlo todo en una competición.",
    highlights: [
      "Flujo offline-first con contenido local",
      "Build web y batería de tests automatizados",
      "Responsive móvil, APK y release checklist todavía en cierre",
    ],
    role: "Producto, frontend y diseño de interacción",
    category: "Juego social",
    status: "En construcción",
    visibility: "principal",
    order: 4,
    stack: ["React", "Vite", "Capacitor", "Vitest"],
    liveUrl: "https://nel386.github.io/punto-medio/",
    liveLabel: "Jugar ahora",
    year: 2026,
  },
  {
    id: "padeltracker",
    title: "Padeltracker",
    description:
      "Una aplicación para registrar partidos, consultar estadísticas y construir un ranking con el tiempo.",
    longDescription:
      "El dominio original ya no está activo. El proyecto sigue formando parte del laboratorio como una pieza en realización, con producto, frontend, backend y despliegue explorados.",
    highlights: [
      "Historial de partidos y evolución por jugador",
      "Flujos para clubes y jugadores amateurs",
      "Infraestructura auto-hosted y despliegues CI/CD",
    ],
    role: "Producto, frontend, backend y despliegue",
    category: "Producto deportivo",
    status: "En realización",
    visibility: "principal",
    order: 5,
    stack: ["Next.js", "TypeScript", "MongoDB", "GitHub Actions"],
    year: 2024,
  },
  {
    id: "aura-draft",
    title: "Aura Draft",
    description:
      "Una carrera social de decisiones y progresión, con momentos que se van construyendo partida a partida.",
    highlights: [
      "Slice vertical jugable con persistencia local",
      "Sistema de encuentros, traits y progresión",
      "La dirección visual y el pack de contenido siguen en construcción",
    ],
    role: "Producto, sistemas de juego y frontend",
    category: "Juego social",
    status: "En construcción",
    visibility: "principal",
    order: 6,
    stack: ["Expo", "React Native", "TypeScript", "SQLite"],
    year: 2026,
  },
  {
    id: "plannel",
    title: "planneL",
    description:
      "Una aplicación de finanzas personales que dejo como registro de una etapa pausada.",
    highlights: [
      "Exploración de SQLite, OCR y transacciones",
      "Sistema de objetivos y funcionalidades por flags",
    ],
    category: "Archivo",
    status: "Pausado",
    visibility: "archivo",
    order: 7,
    stack: ["Expo", "React Native", "SQLite"],
    repoUrl: "https://github.com/nel386/planneL",
    year: 2026,
  },
];
